/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Login;

import database.databaseconnection;
import database.validation;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Banuka Nayanajith
 */
public class edituser extends javax.swing.JDialog {

    /**
     * Creates new form edituser
     */
    String empid;

    public edituser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pw1.grabFocus();
        au.setEnabled(false);

    }

    public edituser(java.awt.Frame parent, boolean modal, String s, String d) {

        super(parent, modal);
        initComponents();
        s = empid;
        System.out.println(s);
        System.out.println(empid);
        au.setEnabled(false);
        un.setText(d);
        pw1.grabFocus();
        //old.setVisible(false);
        jLabel4.setVisible(false);

    }

    public edituser(java.awt.Frame parent, boolean modal, String s) {

        super(parent, modal);
        initComponents();
        au.setEnabled(false);
        un.setText(s);
        //un.setEditable(false);

        old.grabFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        un = new javax.swing.JTextField();
        pw1 = new javax.swing.JPasswordField();
        pw2 = new javax.swing.JPasswordField();
        showcheck = new javax.swing.JCheckBox();
        pwhint = new javax.swing.JTextField();
        au = new javax.swing.JButton();
        old = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        showcheck1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("User Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 6, -1, -1));

        un.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 13)); // NOI18N
        un.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unActionPerformed(evt);
            }
        });
        un.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                unFocusLost(evt);
            }
        });
        un.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unKeyReleased(evt);
            }
        });
        getContentPane().add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 236, 36));

        pw1.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 13)); // NOI18N
        pw1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pw1MouseClicked(evt);
            }
        });
        pw1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pw1ActionPerformed(evt);
            }
        });
        pw1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pw1KeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pw1KeyReleased(evt);
            }
        });
        getContentPane().add(pw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 163, 36));

        pw2.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 13)); // NOI18N
        pw2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pw2ActionPerformed(evt);
            }
        });
        pw2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pw2KeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pw2KeyReleased(evt);
            }
        });
        getContentPane().add(pw2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 163, 36));

        showcheck.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 13)); // NOI18N
        showcheck.setText("Show typed Password");
        showcheck.setEnabled(false);
        showcheck.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                showcheckStateChanged(evt);
            }
        });
        showcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showcheckActionPerformed(evt);
            }
        });
        getContentPane().add(showcheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        pwhint.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 13)); // NOI18N
        pwhint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwhintActionPerformed(evt);
            }
        });
        pwhint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pwhintKeyReleased(evt);
            }
        });
        getContentPane().add(pwhint, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 236, 36));

        au.setText("Save the Details");
        au.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auActionPerformed(evt);
            }
        });
        getContentPane().add(au, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        old.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldActionPerformed(evt);
            }
        });
        old.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                oldKeyReleased(evt);
            }
        });
        getContentPane().add(old, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 172, 37));

        jLabel2.setText("Change the password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 420, -1));

        jLabel3.setText("Password Hint");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel4.setText("Enter your Old Passowrd");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel5.setText("Enter the new password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel6.setText("Repeat your new Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        showcheck1.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 13)); // NOI18N
        showcheck1.setText("Show typed Password");
        showcheck1.setEnabled(false);
        showcheck1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                showcheck1StateChanged(evt);
            }
        });
        showcheck1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showcheck1ActionPerformed(evt);
            }
        });
        getContentPane().add(showcheck1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void unActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unActionPerformed
        String usrcheck = validation.usernameget(un.getText());

        if (usrcheck.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter a validate username");

        }
        pw1.grabFocus();

// TODO add your handling code here:
    }//GEN-LAST:event_unActionPerformed

    private void unKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unKeyReleased

    }//GEN-LAST:event_unKeyReleased

    private void pw1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pw1ActionPerformed

        if (pw1.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter a password to not \n happen this thing next time");
        } else {
            pw2.grabFocus();
        }


    }//GEN-LAST:event_pw1ActionPerformed

    private void pw1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pw1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_pw1KeyReleased

    private void pw1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pw1KeyTyped
        char c = evt.getKeyChar();
        if ((c != 61 && pw1.getText().length() < 6)) {

        } else {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();

        }

    }//GEN-LAST:event_pw1KeyTyped

    private void pw2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pw2ActionPerformed
        if (pw2.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter a password to not \n happen this thing next time");
        } else {
            pwhint.grabFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_pw2ActionPerformed

    private void pw2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pw2KeyReleased
// TODO add your handling code here:
    }//GEN-LAST:event_pw2KeyReleased

    private void pw2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pw2KeyTyped
        char c = evt.getKeyChar();
        if ((c != 61 && pw2.getText().length() < 6)) {

        } else {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_pw2KeyTyped

    private void showcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showcheckActionPerformed

    }//GEN-LAST:event_showcheckActionPerformed

    private void pwhintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwhintActionPerformed
        
        if (pwhint.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter a password hint to not \n happen this thing next time");
        } 
          
    }//GEN-LAST:event_pwhintActionPerformed

    private void pwhintKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwhintKeyReleased
 if(pwhint.getText().length()>0){
  au.setEnabled(true);
 }
                // TODO add your handling code here:
    }//GEN-LAST:event_pwhintKeyReleased

    private void auActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auActionPerformed
        try {

                
                databaseconnection.iud("UPDATE user set user_password='" + pw2.getText() + "',recovery_password='" + pw2.getPassword() + "',user_email='" + pwhint.getText() + "' WHERE user_username='" + un.getText() + "' ");

                un.setText(null);
                showcheck.setSelected(false);
                showcheck1.setSelected(false);
                pw1.setText(null);
                pw2.setText(null);
                pwhint.setText(null);

                this.dispose();
            

        } catch (Exception ex) {
            ex.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_auActionPerformed

    private void unFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_unFocusLost

    private void pw1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pw1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pw1MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed


    }//GEN-LAST:event_formWindowClosed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowLostFocus

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowDeactivated

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden

    }//GEN-LAST:event_formComponentHidden

    private void showcheck1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showcheck1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showcheck1ActionPerformed

    private void oldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oldKeyReleased

    }//GEN-LAST:event_oldKeyReleased

    private void oldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldActionPerformed
        try {
            ResultSet rs = databaseconnection.search("SELECT user_password FROM user WHERE user_username='" + un.getText() + "' ");

            if (rs.first()) {

                if (old.getText().equals(rs.getString(1))) {

                    pwhint.setEditable(true);
                    pw1.setEditable(true);
                    pw2.setEditable(true);
                    showcheck.setEnabled(true);
                    showcheck1.setEnabled(true);
                    pw1.grabFocus();
                } else {
                    System.out.println("NPO");
                    JOptionPane.showMessageDialog(this, "Please enter a correct current password of your account ...");
                    old.grabFocus();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_oldActionPerformed

    private void showcheckStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_showcheckStateChanged
        if (showcheck.isSelected()) {
            pw2.setEchoChar((char) 0);
            pw2.setText(pw2.getText());
        } else {
            pw2.setEchoChar('*');
            pw2.setText(pw2.getText());
        }   // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_showcheckStateChanged

    private void showcheck1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_showcheck1StateChanged
        if (showcheck1.isSelected()) {
            pw1.setEchoChar((char) 0);
            pw1.setText(pw1.getText());
        } else {
            pw1.setEchoChar('*');
            pw1.setText(pw1.getText());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_showcheck1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edituser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edituser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edituser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edituser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                edituser dialog = new edituser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {

                    }
                });
                dialog.setVisible(true);
            }

        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton au;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField old;
    private javax.swing.JPasswordField pw1;
    private javax.swing.JPasswordField pw2;
    private javax.swing.JTextField pwhint;
    private javax.swing.JCheckBox showcheck;
    private javax.swing.JCheckBox showcheck1;
    private javax.swing.JTextField un;
    // End of variables declaration//GEN-END:variables
}
