/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Login;

import database.databaseconnection;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Banuka Nayanajith
 */
public class nullusercrec extends javax.swing.JDialog {

    /**
     * Creates new form nullusercrec
     */
    public nullusercrec(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        un.setText("admin");
        un.setEditable(false);
        pw1.grabFocus();
        au.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel39 = new javax.swing.JLabel();
        pw2 = new javax.swing.JPasswordField();
        pw1 = new javax.swing.JPasswordField();
        jLabel24 = new javax.swing.JLabel();
        un = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        spw = new javax.swing.JLabel();
        showcheck = new javax.swing.JCheckBox();
        jLabel41 = new javax.swing.JLabel();
        au = new javax.swing.JButton();
        useremail = new org.jdesktop.swingx.JXTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);

        jLabel39.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 13)); // NOI18N
        jLabel39.setText("Confirm your password");

        pw2.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 13)); // NOI18N
        pw2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pw2ActionPerformed(evt);
            }
        });
        pw2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pw2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pw2KeyTyped(evt);
            }
        });

        pw1.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 13)); // NOI18N
        pw1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pw1ActionPerformed(evt);
            }
        });
        pw1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pw1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pw1KeyTyped(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 13)); // NOI18N
        jLabel24.setText("Type your password");

        un.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 13)); // NOI18N
        un.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unActionPerformed(evt);
            }
        });
        un.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unKeyReleased(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 13)); // NOI18N
        jLabel23.setText("Username");

        spw.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 13)); // NOI18N
        spw.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        spw.setEnabled(false);

        showcheck.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 13)); // NOI18N
        showcheck.setText("Show typed Password");
        showcheck.setEnabled(false);
        showcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showcheckActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 13)); // NOI18N
        jLabel41.setText("User Email");

        au.setFont(new java.awt.Font("Andale Mono", 0, 13)); // NOI18N
        au.setText("Assign User");
        au.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auActionPerformed(evt);
            }
        });

        useremail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                useremailMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spw, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(au, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(useremail, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(309, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addGap(126, 126, 126)
                            .addComponent(un, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addGap(63, 63, 63)
                            .addComponent(pw1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel39)
                            .addGap(50, 50, 50)
                            .addComponent(pw2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(showcheck))
                        .addComponent(jLabel41))
                    .addGap(0, 189, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(spw, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(useremail, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(au, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel23))
                        .addComponent(un, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(53, 53, 53)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel24))
                        .addComponent(pw1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(pw2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(showcheck)))
                    .addGap(28, 28, 28)
                    .addComponent(jLabel41)
                    .addGap(0, 89, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pw2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pw2ActionPerformed
        useremail.grabFocus();
    }//GEN-LAST:event_pw2ActionPerformed

    private void pw2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pw2KeyReleased
        if (pw1.getText().equals(pw2.getText())) {
            showcheck.setEnabled(true);
            spw.setEnabled(true);
            
        } else {
            showcheck.setEnabled(false);
            spw.setEnabled(false);
        }// TODO add your handling code here:
    }//GEN-LAST:event_pw2KeyReleased

    private void pw2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pw2KeyTyped
        char c = evt.getKeyChar();
        if ((c != 61 && pw2.getText().length() < 6)) {
            
        } else {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_pw2KeyTyped

    private void pw1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pw1ActionPerformed
        pw2.grabFocus();
    }//GEN-LAST:event_pw1ActionPerformed

    private void pw1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pw1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_pw1KeyReleased

    private void pw1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pw1KeyTyped
        char c = evt.getKeyChar();
        if ((c != 61 && pw1.getText().length() < 6)) {
            
        } else {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            
        }

    }//GEN-LAST:event_pw1KeyTyped

    private void unActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_unActionPerformed

    private void unKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unKeyReleased

    }//GEN-LAST:event_unKeyReleased

    private void showcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showcheckActionPerformed
        if (pw1.getText().equals(pw2.getText())) {
            if (spw.isVisible()) {
                user_Login ul = new user_Login();
                this.add(ul);
                ul.setVisible(true);
                this.setSize(700, 500);
            }
            spw.setText(pw2.getText());
            au.setEnabled(true);
            useremail.grabFocus();
            
        } else {
            spw.setText("");
            spw.setEnabled(false);
            pw2.setText(null);
            pw2.grabFocus();
        }   // TODO add your handling code here:
    }//GEN-LAST:event_showcheckActionPerformed

    private void auActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auActionPerformed
        try {
            if (!un.getText().isEmpty() && !useremail.getText().isEmpty() && pw1.getPassword().length > 0) {
                
                if (database.validation.emailtxt(useremail)) {
                    databaseconnection.iud("INSERT INTO user (user_username,user_password,recovery_password,user_email,user_status_iduser_status)VALUES('" + un.getText() + "','" + pw2.getText() + "','" + pw2.getPassword() + "','" + useremail.getText() + "','1')");
                    user_Login ul = new user_Login();
                    this.add(ul);
                    ul.setVisible(true);
                    this.setSize(700, 500);
                    un.setText(null);
                    pw1.setText(null);
                    pw2.setText(null);
                    useremail.setText(null);
                    showcheck.setSelected(false);
                    spw.setText(null);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Please enter a correct email");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please enter required field");
                
            }
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_auActionPerformed

    private void useremailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_useremailMouseClicked
        if (useremail.getText().equals("Email is invalid")) {
            useremail.setForeground(Color.BLACK);
            useremail.setText("");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_useremailMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nullusercrec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nullusercrec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nullusercrec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nullusercrec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                nullusercrec dialog = new nullusercrec(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setFocusable(true);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton au;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JPasswordField pw1;
    private javax.swing.JPasswordField pw2;
    private javax.swing.JCheckBox showcheck;
    private javax.swing.JLabel spw;
    private javax.swing.JTextField un;
    private org.jdesktop.swingx.JXTextField useremail;
    // End of variables declaration//GEN-END:variables
}
