/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Login;

import database.databaseconnection;
import database.validation;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author vextroidMAC
 */
public class user_Login extends javax.swing.JPanel {

    int xmouse;
    int ymouse;

    String postype;
    String user;
    String name;
    int count;
    int status;
    String emp;

    Date d;
    SimpleDateFormat sdf;
    String devusername = "dvlpr";
    String devpassword = "qwe";

    public user_Login() {
        initComponents();
        loadtime_date();
        password.setTransferHandler(null);
        jSeparator1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        username = new org.jdesktop.swingx.JXTextField();
        password = new javax.swing.JPasswordField();
        PASS_TEX = new javax.swing.JLabel();
        loginb = new org.jdesktop.swingx.JXButton();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Login/Images/user_256px.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 270, 280));

        username.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        username.setOpaque(false);
        username.setPrompt("USER NAME");
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 260, 20));

        password.setOpaque(false);
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 260, 20));

        PASS_TEX.setForeground(new java.awt.Color(91, 91, 95));
        PASS_TEX.setText("PASSWORD");
        PASS_TEX.setOpaque(true);
        add(PASS_TEX, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 430, 80, 20));

        loginb.setText("Login");
        loginb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbActionPerformed(evt);
            }
        });
        add(loginb, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 260, -1));

        jXLabel1.setText("Username :");
        add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 60, -1));

        jXLabel2.setText("Password :");
        add(jXLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 60, -1));

        jLabel2.setText("Forgot your password?");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 504, 130, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 518, 110, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        password.setText("");
        password.grabFocus();
    }//GEN-LAST:event_usernameActionPerformed

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        password.setText("");
        PASS_TEX.setVisible(false);
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        if (new String(password.getPassword()).equals("")) {
            PASS_TEX.setVisible(true);
        }
    }//GEN-LAST:event_passwordFocusLost

    private void loginbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbActionPerformed
        try {
            String p = new String(password.getPassword());

            boolean b = false;

            if (username.getText().equals(devusername) && new String(password.getPassword()).equals(devpassword)) {
                postype = "dvlpr";
                user = "dvlpr";

                //home h = new home(postype, user);
                //h.setVisible(true);
                //this.dispose();
            } else {
                ResultSet rs1 = databaseconnection.search("SELECT * FROM user WHERE user_username='" + username.getText() + "'");
                if (rs1.first()) {
                    if (rs1.getInt("status") == 1) {
                        if (!p.startsWith("[C")) {
                            b = logincheck();

                        } else {
                            b = logincheckwithr();

                            emp = rs1.getString("emp_id");
                            System.out.println(emp);
                            edituser edu = new edituser(null, true, emp, username.getText().toString());
                            edu.empid = emp;
                            edu.setVisible(true);

                        }

                        if (b) {
                            ResultSet rs = databaseconnection.search("SELECT * FROM user WHERE user_username='" + username.getText() + "'");

                            if (rs.first()) {

                               // postype = rs.getString("position");
                                // user = rs.getString("efname") + " " + rs.getString("elname");
                                // home h = new home(postype, user);
                                System.out.println(postype + " " + user);
                                //h.setVisible(true);

                            } else {
                                //postype = "admin";
                                //user = "admin";

                               // home h = new home(postype, user);
                                //   h.setVisible(true);
                            }

                        } else {
                            name = username.getText();
                            System.out.println(name);
                            count++;
                            System.out.println(count);

                            if (name.equals(username.getText())) {

                                switch (count) {

                                    case 1:
                                        JOptionPane.showMessageDialog(this, "4 Attempts are Remaining\nCheck your username and password ...", "Login Attempts Faild", JOptionPane.WARNING_MESSAGE);
                                        break;
                                    case 2:
                                        JOptionPane.showMessageDialog(this, "3 Attempts are Remaining\nCheck your username and password ...", "Login Attempts Faild", JOptionPane.WARNING_MESSAGE);
                                        break;
                                    case 3:
                                        JOptionPane.showMessageDialog(this, "2 Attempts are Remaining\nCheck your username and password ...", "Login Attempts Faild", JOptionPane.WARNING_MESSAGE);
                                        break;
                                    case 4:
                                        JOptionPane.showMessageDialog(this, "1 Attempts are Remaining\nCheck your username and password ...", "Login Attempts Faild", JOptionPane.WARNING_MESSAGE);
                                        break;
                                    default:
                                        JOptionPane.showMessageDialog(this, "Your account is locked..\n Please use forget password function to get your recovery code", "Login Attempts Faild", JOptionPane.WARNING_MESSAGE);
                                        databaseconnection.iud("UPDATE user set status='0' WHERE username='" + username.getText() + "' ");
                                        break;
                                }
                            } else {
                                name = "";
                                count = 0;

                            }
                        }

                    } else {
                        JOptionPane.showMessageDialog(this, "Your Account has been deleted or locked..\n Please contact the admin");
                    }

                }
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_loginbActionPerformed

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        username.setText("");
    }//GEN-LAST:event_usernameFocusGained

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        if (!username.getText().equals("USERNAME") && username.getText().length() != 0) {
            try {

                String email = JOptionPane.showInputDialog(this, "Enter your email address");

                if (!email.equals("")) {
                    email = validation.emailget(email);

                    if (email.equals("wrong")) {
                        throw new Exception();
                    }
                    ResultSet rs = databaseconnection.search("SELECT re.eemail FROM regemployee re INNER JOIN user u ON u.emp_id=re.regEMPid WHERE u.username='" + username.getText() + "' ");
                    ResultSet rs2 = databaseconnection.search("SELECT recover_password FROM user WHERE username='" + username.getText() + "' ");
                    String rec = "";
                    if (rs2.first()) {
                        rec = rs2.getString(1);
                    }
                    if (rs.first()) {
                        if (rs.getString(1).equals(email)) {

                            String from = "flowerfactory95@gmail.com";
                            String epassword = "vextroid1996";
                            String[] to = {rs.getString(1)};
                            String host = "smtp.gmail.com";

                            Properties prop = System.getProperties();
                            prop.put("mail.smtp.starttls.enable", "true");
                            prop.put("mail.smtp.host", host);
                            prop.put("mail.smtp.user", from);
                            prop.put("mail.smtp.password", password);
                            prop.put("mail.smtp.port", "587");
                            prop.put("mail.smtp.auth", "true");

                            Session sees = Session.getDefaultInstance(prop);
                            MimeMessage msg = new MimeMessage(sees);
                            msg.setFrom(new InternetAddress(from));
                            InternetAddress[] add = new InternetAddress[to.length];
                            for (int i = 0; i < to.length; i++) {
                                add[i] = new InternetAddress(to[i]);

                            }
                            for (int i = 0; i < add.length; i++) {
                                msg.setRecipient(Message.RecipientType.TO, add[i]);
                            }
                            msg.setSubject("Login Recovery");
                            msg.setContent("This is your Recovery Password..\n Copy this and enter this password field..\n " + rec + " ", "text/html; charset=utf-8");

                            Transport trans = sees.getTransport("smtp");
                            trans.connect(host, from, epassword);
                            trans.sendMessage(msg, msg.getAllRecipients());
                            trans.close();
                            JOptionPane.showMessageDialog(this, "Password send\nCheck your email to get your password");

                        } else {
                            JOptionPane.showMessageDialog(this, "Please enter your email for this username", "WARNING", JOptionPane.WARNING_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Please enter valid username", "WARNING", JOptionPane.WARNING_MESSAGE);
                    }
                }

            } catch (NullPointerException ex) {

            } catch (Exception e) {
                //JOptionPane.showMessageDialog(this, "Please enter a vald email");
                //jButton1.doClick();
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Enter your username first", "WARNING", JOptionPane.WARNING_MESSAGE);
            username.grabFocus();
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jSeparator1.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jSeparator1.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PASS_TEX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXButton loginb;
    private javax.swing.JPasswordField password;
    private org.jdesktop.swingx.JXTextField username;
    // End of variables declaration//GEN-END:variables

    private void loadtime_date() {
        try {

            Timer timer = new Timer(1000, new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {

                    d = new Date();
                    sdf = new SimpleDateFormat("dd/MM/yyyy");
                    SimpleDateFormat sdf1 = new SimpleDateFormat();

                    sdf = new SimpleDateFormat("hh:mm a");
                    sdf1 = new SimpleDateFormat("hh:mm:ss a");

                    if (sdf1.format(d).equals("10:00:00 AM")) {
                        try {
                            String ti = "TBACK";
                            databaseconnection.BackupDatabase(ti);
                        } catch (Exception ex) {
                            ex.printStackTrace();
                        }
                    }
                    if (sdf1.format(d).equals("12:00:00 PM")) {
                        try {
                            String ti = "TBACK";
                            databaseconnection.BackupDatabase(ti);
                        } catch (Exception ex) {
                            ex.printStackTrace();
                        }
                    }
                    if (sdf1.format(d).equals("03:00:00 PM")) {
                        try {
                            String ti = "TBACk";
                            databaseconnection.BackupDatabase(ti);

                        } catch (Exception ex) {
                            ex.printStackTrace();
                        }
                    }

                }
            });
            timer.start();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public Boolean logincheck() {
        try {
            String p = new String(password.getPassword());

            String username23 = this.username.getText();
            String password23 = p;
            Connection conn = databaseconnection.newCon();
            String sql = "SELECT * FROM  user Where user_username=?"
                    + "AND user_password =?";

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, username23);
            ps.setString(2, password23);

            ResultSet rs = ps.executeQuery();
            if (rs.next()) {

                return true;
            } else {
                return false;
            }

        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }

    public Boolean logincheckwithr() {
        try {
            String p = new String(password.getPassword());

            String username = this.username.getText();
            String password = p;
            Connection conn = databaseconnection.newCon();
            String sql = "SELECT * FROM  user Where user_username=?"
                    + "AND recovery_password =?";

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, username);
            ps.setString(2, password);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {

                return true;
            } else {

                return false;
            }

        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
}
